name: .NET Core

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/kleinrechner/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Install dependencies  
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Build and generate SplishSplash.Hub.Authentication.Abstractions NuGet package
      run: dotnet pack SplishSplash.Hub.Authentication.Abstractions/SplishSplash.Hub.Authentication.Abstractions.csproj --no-build --configuration Release --output nuget/SplishSplash.Hub.Authentication.Abstractions    
    
    - name: Build and generate SplishSplash.Hub.Authentication NuGet package
      run: dotnet pack SplishSplash.Hub.Authentication/SplishSplash.Hub.Authentication.csproj --no-build --configuration Release --output nuget/SplishSplash.Hub.Authentication

    - name: Push generated SplishSplash.Hub.Authentication.Abstractions package to GitHub registry
      run: dotnet nuget push nuget/SplishSplash.Hub.Authentication.Abstractions/*.nupkg --skip-duplicate --no-symbols true  
    
    - name: Push generated package SplishSplash.Hub.Authentication to GitHub registry
      run: dotnet nuget push nuget/SplishSplash.Hub.Authentication/*.nupkg --skip-duplicate --no-symbols true
